### ISSUE TITLE
Set up semantic versioning for our PyPi package

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/rapid-router#1013]
## Task Description
To help us better manage our deployment process and help us in upgrading our dependencies. It would be helpful to set up [semantic versioning](semver.org).

## Acceptance Criteria
- [x] Travis CI deploys a new version
- [x] we specify a version
- [x] there is a check on PR that we have updated the version
- [ ] deployment pipeline takes beta releases on dev and staging by default and stable releases on production

## Analytics Requirements
N/A
