### ISSUE TITLE
Use common package

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1114]
## Task Description
Use the common package created in [1226](https://app.zenhub.com/workspaces/code-for-life-development-56f2afba6e54555c586f6db3/issues/ocadotechnology/codeforlife-portal/1226) so that the models import common's models instead of portal's.

This is the first step towards fixing #688.

## Acceptance Criteria
- [ ] Common package is installed, added to requirements and apps.
- [ ] The following models' foreign keys to portal's models has been updated to point to common's models:
- [ ] Level
- [ ] Workspace
- [ ] Attempt
- [ ] All other instances where portal models were imported have been updated
