### ISSUE TITLE
Levels 106 - 109: Replace `n` with `number` (UKS3-S15)

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1194]
## Task Description
The solutions for levels 106-109 use while loops with an iterator variable called `n`. We want to rename that variable to `number`.
This change will also to be reflected in the USK3-S15 teaching materials as well as the solutions in the solutions table.

## Acceptance Criteria
- [ ] `n` replaced with `number` in model solutions for levels 106-109 in the code.
- [ ] `n` replaced with `number` in the USK3-S15 lesson plan (also check supporting material for this session) in Gitbook
- [ ] Solutions updated in the solutions table in Gitbook

**Comment by faucomte97** [comment]
And maybe all other one-letter vars

**Comment by lauracumming** [comment]
@faucomte97 should this be an investigation task to discover the work involved over resources and dev?

**Comment by lauracumming** [comment]
@faucomte97

**Comment by faucomte97** [comment]
Yes, replace with number

**Comment by faucomte97** [comment]
https://docs.google.com/document/d/145L-b6qFSpJD-J33BcoiI8XeTTzjG--3Ys0Y9KjGKF4/edit#

**Comment by SKairinos** [comment]
@evemartin completed this task
