### ISSUE TITLE
Rapid Router later levels updates - stage 1 (change colours, remove Dee)

### ISSUE THREAD

**Issue by razvan-pro** [ocadotechnology/rapid-router#1323]
## Task Description
Update colours and Dee on later levels.

## Acceptance Criteria
- [ ] Update colours on Levels page
- [ ] Update sidebar colour based on episode
- [ ] Replace Dee with Bav on brain teaser levels
- [ ] Remove Dee on Python levels

### Analytics Requirements
None

### Copywrite Requirements
Miro
