### ISSUE TITLE
Administrator power - Levels page

### ISSUE THREAD

**Issue by razvan-pro** [ocadotechnology/rapid-router#1340]
## Task Description

For admin teachers update the Levels page of Rapid Router to show levels created by other teachers and students in the school.

## Acceptance Criteria

- [ ] Show other levels in "Levels shared with you". Users should have their name in brackets.
- [ ] Admin teacher can access and share any levels in the school
- [ ] Admin teacher can share levels with any class in the school (show teacher name in brackets)
- [ ] Show admin teachers in Share tab when teachers are selected. They should be greyed out with "Yes" and not allow changing.
- [ ] Update Share text only for teachers
- [ ] In Load tab (in the game), "Shared levels" option should show the levels for all teachers and students in the school if the teacher is an admin

## Copywrite Requirements

Miro

## Analytics Requirements

None
