### ISSUE TITLE
Administrator power - Level moderation

### ISSUE THREAD

**Issue by razvan-pro** [ocadotechnology/rapid-router#1341]
## Task Description

Update the level moderation page to include all students' levels for admin teachers.

## Acceptance Criteria

- [ ] Include all school students in the table for admin teachers
- [ ] Update the student name column to show their teacher for admin teachers
- [ ] Allow the admin teacher to moderate (delete) any school levels

## Copywrite Requirements

Miro

## Analytics Requirements

TBC
