### ISSUE TITLE
Rapid Router later levels updates - stage 2 (Python windows/button update)

### ISSUE THREAD

**Issue by dionizh** [ocadotechnology/rapid-router#1346]
## Task Description

Update RR python console to bridge to Kurono. See Miro for design.

## Acceptance Criteria
- [x] Make sections draggable/moveable between the code and console
- [x] Add console log bar
- [x] Add 'Run code' button
- [x] Add 'Clear console' button
- [x] Add test for the run button
- [x] Add test for the clear button
- [x] Update icons on the sidebar

### Analytics Requirements
None

### Copywrite Requirements
Miro
