### ISSUE TITLE
Scoreboard update - loading - text

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1350]
## Task Description
Load all levels by default and update text. Also amend the fixed columns.

## Acceptance Criteria
- [ ] Have all levels checked by default.
- [ ] Update text above dropdowns.
- [ ] Update the fixed columns in the table.

### Analytics Requirements
None

### Copywrite Requirements
Miro
