### ISSUE TITLE
Scoring/Tracking for level editor

### ISSUE THREAD

**Issue by razvan-pro** [ocadotechnology/rapid-router#1357]
## Task Description
Add a scoring table for custom levels.

## Acceptance Criteria
- [ ] Create a new table for shared levels on scoreboard page
- [ ] Add 'Not available' (or icon) to levels not shared
- [ ] Add level name and ownership to header
- [ ] Make table available for students too (just for them and levels they have access to)

### Analytics Requirements
None

### Copywrite Requirements
Miro
