### ISSUE TITLE
Rapid Router later levels updates - stage 3 (resizable Python IDE, new popup buttons and styles)

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1367]
## Task Description
The Python window in Rapid Router Python levels should grow and shrink as the slider gets moved. The buttons in the popups should also have the new styling and allow the user to navigate to the previous and the next levels.

## Acceptance Criteria
- [ ] The Python window updates in size as the slider gets moved.
- [x] Add "Previous Level" button
- [x] Add "Next Level" button
- [x] Move / Put "Play" button in between them
- [x] Update button styles to match designs

### Analytics Requirements
None

### Copywrite Requirements
[Miro](https://miro.com/app/board/uXjVO-NNCyU=/)
