### ISSUE TITLE
set instructions and hints when creating levels

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1407]
## Task Description
Before each level there is a pop-up that explains what the player will need to do to be successful. It would be a good idea to make this accessible in the level editor as currently once a custom level is created, the instructions are minimal and the help text is even worse.

## Acceptance Criteria
- [ ] New text box for level instruction
- [ ] New text box for help text instruction
- [ ] Save button to apply the changes
- [ ] Edit button to edit the text

### Analytics Requirements
- [ ] track usage 

### Copywrite Requirements
- [ ] Please add an instruction for your level here
- [ ] Please add a 'help' hint for your level here

**Comment by faucomte97** [comment]
@lauracumming Create task in design for grads

**Comment by faucomte97** [comment]
Done!
