### ISSUE TITLE
Add new sound effects for Santa's Sleigh

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1556]
## Task Description
In December, the Van is replaced by Santa's Sleigh with Rapid Rudolph and all the levels become snow levels!
However, the sound effects remain the Van's sound effects, including the van's engine sound and the horn. Let's add in two new sound files for the Sleigh to turn those into festive sounds.

These sounds can both be heard in action in [level 38](https://www.codeforlife.education/rapidrouter/38/#myModal), for example.

## Acceptance Criteria
- [ ] Ask a member of the team for the sound files.
- [ ] Load in the sleigh bells sound instead of the engine startup sound  **only when it's December**.
- [ ] Load in the clown horn sound instead of the van horn sound  **only when it's December**.

**Comment by alkezz** [comment]
Hello! I'd like to work on this issue if possible :)

**Comment by faucomte97** [comment]
Hi @alkezz, of course! Before you start, please can you read through our [Contributor Agreement](https://github.com/ocadotechnology/codeforlife-workspace/blob/main/CONTRIBUTING.md) and follow the steps at the bottom of the file so we can verify and add you as an official contributor.

Feel free to start the work on the task too but we will only be able to approve PR check runs, review and merge the PR once you've become an official contributor on the list.

**Comment by evemartin** [comment]
Update with sound files: 

[Ho ho ho](https://pixabay.com/sound-effects/ho-ho-ho-merry-christmas-santa-claus-181123/) - use this when the sleigh crashes
[Jingle bells 1](https://pixabay.com/sound-effects/jingle-bells-107671/), [jingle bells 2](https://pixabay.com/sound-effects/sleigh-bells-shaking-67086/), and [jingle bells 3 ](https://pixabay.com/sound-effects/sleigh-bells-7-22-12-edit-99843/)- choose one to use when the sleigh starts

**Comment by bella054** [comment]
I'm happy to be assigned to this issue please!

**Comment by SKairinos** [comment]
@faucomte97 and @lauracumming , which clown horn sound did we want to use?

**Comment by lauracumming** [comment]
We should say thanks to all the folk that have created these sounds somewhere @faucomte97 @SKairinos - can we in the code comments or something?

**Comment by lauracumming** [comment]
Sound Effect by <a href="https://pixabay.com/users/freesound_community-46691455/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=44595">freesound_community</a> from <a href="https://pixabay.com/sound-effects//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=44595">Pixabay</a>

**Comment by SKairinos** [comment]
@bella054 , could you please [create a pull request](https://github.com/bella054/rapid-router/pulls) for this task into our main branch? Otherwise we can't merge your changes in. Thank you! :)

**Comment by SKairinos** [comment]
@bella054 , just a reminder to create your pull request. let me know if you need help
