### ISSUE TITLE
Add drop down into nav bar on Rapid Router to introduce translater

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1600]
## Task Description
Add a drop down into the nav bar in Rapid Router in order to add the option to translate the blocks.

## Acceptance Criteria
- [ ] drop down added to Nav bar
- [ ] [set the user's preferred language](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages) as the default language

### Analytics Requirements
- [ ] Create tag in tag manager to track clicks

Something like this would be great: https://www.figma.com/file/6802Amjc4GKRdqzm26ozaw/While-Loop-levels?type=design&node-id=114%3A638&mode=design&t=S49ZCz1J60y1ePHG-1

**Comment by lauracumming** [comment]
@faucomte97 @SKairinos please groom for @evemartin
