### ISSUE TITLE
Copy of Add drop down into nav bar on Rapid Router to introduce translater

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1603]
## Task Description
Add a drop down into the nav bar in Rapid Router in order to add the option to translate the blocks.

## Acceptance Criteria
- [ ] drop down added to Nav bar
- [ ] [set the user's preferred language](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages) as the default language

### Analytics Requirements
- [ ] Create tag in tag manager to track clicks

Something like this would be great: https://www.figma.com/file/6802Amjc4GKRdqzm26ozaw/While-Loop-levels?type=design&node-id=114%3A638&mode=design&t=S49ZCz1J60y1ePHG-1

**Comment by lauracumming** [comment]
- [ ] production approved

Adding tasks for 'do'

**Comment by lauracumming** [comment]
- [ ]  Check Cookie banner: banner loads, categories in the right order, cookies disabled by default
- [ ]  Check Rapid Router: game loads, can solve a level, can save a workspace, can create a level, can save a level, scores get saved, scoreboard loads
- [ ]  Check OS on browserstack

**Comment by SKairinos** [comment]
@faucomte97, is this block correct?
<img width="221" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemdHQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f4427c25796ff6a4ce0e10171f021e8d839ae256/image.png" alt="image.png" />

**Comment by faucomte97** [comment]
yes

**Comment by evemartin** [comment]
new PR just for adding do: https://github.com/ocadotechnology/rapid-router/pull/1623

**Comment by lauracumming** [comment]
checker 2 needed

**Comment by faucomte97** [comment]
Staging looks good to me.

**Comment by lauracumming** [comment]
Prod - LGTM

**Comment by faucomte97** [comment]
LGTM
