### ISSUE TITLE
Level editor - level introduction and hint textboxes - backend

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1628]
## Task Description
We would like to give users the ability to add in an instruction and a hint within the level creator instead of it being generic and not particularly useful. There would still need to be a generic solution applied, so that it is optional.

## Acceptance Criteria
- [ ] Add instruction panel
- [ ] Add hint text panel

### Analytics Requirements
- [ ] Track with Tag manager

### Copywrite Requirements
Links to designs are here: https://drive.google.com/drive/folders/13za5V1SIG22UPZtJren5nI5CpdcKnxUq?usp=drive_link

**Comment by evemartin** [comment]
@lauracumming do you have any specific SVG files you'd like me to use for the instruction and hint panel icons?

**Comment by lauracumming** [comment]
yes, how do you need them supplying, is it just the icon itself, or do you need the whole button?

**Comment by lauracumming** [comment]
There is this that could be used for hint: https://drive.google.com/file/d/0B7tWuEK9av7dTTI5RWtYTk8xV3M/view?usp=drive_link&resourcekey=0-HwQVpUaRPYOPrYFNkLdvBg

**Comment by lauracumming** [comment]
I'll check it in Illustrator

**Comment by lauracumming** [comment]
There is an instruction too:https://drive.google.com/file/d/1_r2__MrDApuYqHc27Di015JThWJQ2waG/view?usp=drive_link

**Comment by lauracumming** [comment]
Ah - okay - so just use Material if it's just icons.

**Comment by lauracumming** [comment]
Material UI

**Comment by evemartin** [comment]
The issue with the changes to default levels has now been fixed by [this PR](https://github.com/ocadotechnology/rapid-router/pull/1657)!

**Comment by lauracumming** [comment]
LGTM

**Comment by lauracumming** [comment]
LGTM

**Comment by lauracumming** [comment]
I discovered that if you add emojis to the descriptions it errors though[Uploading... Screenshot 2024-06-28 at 15.01.07.png]

**Comment by faucomte97** [comment]
Screenshot hasn't come through - please reupload or describe in your own words

**Comment by faucomte97** [comment]
Confirmed emoji bug - probably to do with string format. Cf error log: https://console.cloud.google.com/errors/detail/CJH_3ZfvnvvCFA;service=default;version=169;time=P1D?project=decent-digit-629

**Comment by evemartin** [comment]
I have created this task to address the emoji bug! https://app.zenhub.com/workspaces/code-for-life-development-56f2afba6e54555c586f6db3/issues/gh/ocadotechnology/rapid-router/1661

**Comment by faucomte97** [comment]
Thanks @evemartin - this task LGTM otherwise
