### ISSUE TITLE
Copy of Level editor - level introduction text

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1629]
## Task Description
We would like to give users the ability to add in an instruction and a hint within the level creator instead of it being generic and not particularly useful. There would still need to be a generic solution applied, so that it is optional.

## Acceptance Criteria
- [ ] Add instruction panel
- [ ] Add hint text panel

### Analytics Requirements
- [ ] Track with Tag manager

### Copywrite Requirements
Links to designs are here: https://drive.google.com/drive/folders/13za5V1SIG22UPZtJren5nI5CpdcKnxUq?usp=drive_link

**Comment by lauracumming** [comment]
It did copy it twice
