### ISSUE TITLE
Level editor - level instruction and hint text UI

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1630]
## Task Description
We would like to give users the ability to add in an instruction and a hint within the level creator instead of it being generic and not particularly useful. There would still need to be a generic solution applied, so that it is optional.

## Acceptance Criteria
- [ ] Add instruction panel UI
- [ ] Add hint text panel UI

### Analytics Requirements
- [ ] Track with Tag manager

### Copywrite Requirements
Links to designs are here: https://drive.google.com/drive/folders/13za5V1SIG22UPZtJren5nI5CpdcKnxUq?usp=drive_link

**Comment by evemartin** [comment]
I've added tracking to Tag Manager but I don't see a submit or publish button - I think I might have had my access revoked or never had access to begin with. Could someone please add me?

**Comment by SKairinos** [comment]
what is the aim and what is the instruction in this example?
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU5rQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc990df6d3d85e1b2973a65e49c9a32070e83d62/image.png" alt="image.png" />

**Comment by lauracumming** [comment]
Instruction is how to tackle the level and what to expect, the hint is just a clue on how to solve it.

**Comment by lauracumming** [comment]
Instruction pops up at the start of a level, hint pops up if you press the hint button, or now, in this new case, if you struggle on a level (crash X times)

**Comment by evemartin** [comment]
Just to confirm, one of the changes I'm implementing based on our discussion this morning is that there will be a "display hint" button on every failure popup and the teacher won't be able to configure this to make it so that the hint only shows up after X attempts. Is that correct?

**Comment by lauracumming** [comment]
Yes, we will add button directly to failure pop-up. Im not sure how the transition from failure pop-up to hit pop-up will look, will have to test. 

Currently the hint/help pop-up contains a button that says 'close', but I think it should echo the general pop-up and have the play button with the cross icon representing close to keep the labelling consistent.

**Comment by lauracumming** [comment]
I can create a separate task for this.

**Comment by faucomte97** [comment]
LGTM, however it was possible to set a subtitle > 100 chars. @evemartin Not sure how that was possible given the constraint on the model field, but it's not causing an actual issue UX wise

**Comment by evemartin** [comment]
I've just checked and it seems like apparently SQLite doesn't actually enforce max length constraints on TextFields or CharFields - maybe that's why?

**Comment by evemartin** [comment]
The issue with the changes to default levels has now been fixed by [this PR](https://github.com/ocadotechnology/rapid-router/pull/1657)!

**Comment by lauracumming** [comment]
LGTM

**Comment by lauracumming** [comment]
LGTM - see comment on other ticket about emojis

**Comment by faucomte97** [comment]
LGTM
