### ISSUE TITLE
Add two languages

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1637]
## Task Description

We would like to add two more languages to RR

## Acceptance Criteria
- [x] Add  2 verified languages to the blocks

### Analytics Requirements
- [ ] Track clicks of dropdown

### Copywrite Requirements
- [ ] As per doc: https://docs.google.com/document/d/1hXE7yKPf7_r_OTijbFZxnHKpohn_XvwLH8kBYhCvPoQ/edit?usp=sharing

**Comment by evemartin** [comment]
Verified languages: Catalan, Bulgarian?

**Comment by lauracumming** [comment]
LGTM

**Comment by faucomte97** [comment]
LGTM
