### ISSUE TITLE
Autosave in level editor

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1639]
## Task Description
As a logged in user I would like it if every time I edited a level, it would autosave so that I don't lose my work.

## Acceptance Criteria
- [ ] Game should autosave level editor state on any state change on the DB (only for logged in users)
- [ ] Add a last_saved_at field on the Level model and auto generate names with "Untitled X" convention where X is a number.
- [ ] Make name & owner unique together.

### Analytics Requirements
- [ ] None

### Copywrite Requirements
- [ ] @lauracumming
