### ISSUE TITLE
Remove direct drive arrows

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1662]
## Task Description
Rapid Router levels 1-18 have a feature that we call "direct drive arrows".

![image](https://github.com/ocadotechnology/rapid-router/assets/33633200/7c9f5a8d-6606-4ccc-a3f0-caa1a12ac8bf)

They were originally put in to help young learners with directing the van, however over the last few years, various workshops and school visits have highlighted that the arrows cause more confusion than clarity. As the van moves after a arrow press, the equivalent block is added to the workspace (even if the block isn't originally available in the level), and if the van drives off the road, there is no instant feedback that the van would crash.
The left & right arrows also causes extra confusion as they are from the player's perspective instead of the van's.

Because of this, we've decided to remove the feature completely.

## Acceptance Criteria
- [x] Remove the direct drive arrows from levels 1 through 18.
- [x] Delete any associated code - eg, if there is a toggle on the level to enable the arrows, or any other functionality around the arrows - that should go too.
- [x] Delete any images, icons and assets used for the arrows.
- [x] Double-check the description and hint texts for levels 1 through 18. Any reference to the direct drive arrows should be removed / updated.
- [x] Also double-check the teaching materials for levels 1 through 18 - these probably have references to the arrows too. Make a note of these and the full time team know so we can make the relevant updates to the teaching materials.

## Good places to start:

- Main game page: https://github.com/ocadotechnology/rapid-router/blob/master/game/templates/game/game.html
- Setup function for the direct drive: https://github.com/ocadotechnology/rapid-router/blob/master/game/static/game/js/game.js#L333
- Direct drive assets in here: https://github.com/ocadotechnology/rapid-router/tree/master/game/static/game/image/actions
- Direct drive boolean on Level model (will no longer be relevant once this task is done): https://github.com/ocadotechnology/rapid-router/blob/master/game/models.py#L163

**Comment by razvan-pro** [comment]
References to the arrows in the teaching materials:
* https://code-for-life.gitbook.io/teaching-resources/rapid-router-ks1-teaching-resources/ks1-sessions/ks1-session-2 - A sentence references the Go button.
* https://code-for-life.gitbook.io/teaching-resources/rapid-router-ks1-teaching-resources/ks1-sessions/ks1-session-3 - It has a few references to the buttons, one of them is a block with an image. Search for "direct drive" on the page.

**Comment by faucomte97** [comment]
Now on our staging website. Reminder to myself that the teaching materials need to be updated when we deploy this to prod.

**Comment by lauracumming** [comment]
LGTM

**Comment by lauracumming** [comment]
LGTM
