### ISSUE TITLE
Clarify the purpose of the bin history menu

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1666]
## Task Description
Rapid Router has a "bin" feature, allowing the player to drag and drop blocks to the bin to discard them.
After that, the player may click the bin to reveal the "bin history" i.e. what's been discarded since the start of the level, allowing them to retrieve past blocks. This shows up in a grey side bar on the right hand side of blocks space.

![image](https://github.com/ocadotechnology/rapid-router/assets/33633200/cce934ad-d935-469e-aa2a-adb2e5f65877)

We feel the "bin history" might not be immediately obvious so we need to make it clearer.

## Acceptance Criteria
- [ ] Add a piece of text inside the grey bar to label it.
- [ ] "Bin history" is an option - confirm this with @lauracumming.
- [ ] The placement of the text should probably be at the top of the grey bar - confirm this with @lauracumming.
- [ ] BONUS: The "bin history" always seems to contain a "Start" block. This is an issue because it allows players to drag a new Start block to the game which breaks it. Bonus points if you can remove that Start block from the bin history.

**Comment by GlorygloryK** [comment]
Idea for title : Bin basket ( instead of bin history?)- implies that you can retrieve  things you've put in the bin, once you've 'binned' it

**Comment by bella054** [comment]
Hi, happy to be assigned to this one please!

**Comment by SKairinos** [comment]
Hello. We recommend you pick up another task. We have realised this task is too hard for contributors.

**Comment by faucomte97** [comment]
Closing as we need to upgrade Blockly first.
