### ISSUE TITLE
Python Den levels page

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1673]
## Task Description
We would like to build the page for the Python Den levels - it will replicate Rapid Router levels page. In order to complete this task, the Python levels will be separated from RR, and the new mapping will be applied throughout. There will be levels that need remapping, and button with links to videos and resources.

## Acceptance Criteria
- [ ] Remove Python levels from Rapid Router levels page
- [ ] Add Python levels to Python Hub levels page

### Analytics Requirements
- [ ] Track page views through GA (#1178)
- [ ] Track button clicks through tag manager (#1178)

### Copywrite Requirements
- [ ] Copy for page is here

*Note: There are different views for different users*

**Comment by evemartin** [comment]
Important links:
- Figma designs https://www.figma.com/design/9pMg7hFzK5YkjcnmwZsFl1/Portal-UI?node-id=182-2184&t=VWyykF7x3I4EB9kB-0
- Level mapping layout https://docs.google.com/document/d/1y_HvqeOQ9gY4IABN47XEYjNSDwNqWVlZm02psUtibMA/edit
- Design components https://www.figma.com/design/YKyygZLaS9LipvkyahRFxW/Design-system?node-id=1836-1252&t=ERfZuF92CrbmCHgh-0

**Comment by lauracumming** [comment]
Updated designs for high level build<img width="557" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTRGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e94f76aed507b20a6ae2b6e6dcf58aab5d1c6d94/Python%20Den%20page%20with%20buttons%20closed.png" alt="Python Den page with buttons closed.png" />
<img width="414" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeThGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbc17c7a935c87c06513cc887e2e978f9cc9e8a4/Python%20Den%20page%20with%20buttons%20open%20-%20Independent%20student%20view.png" alt="Python Den page with buttons open - Independent student view.png" />
<img width="414" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekFGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bce5cb2e11a5fe7afd7617bc4af89f881f7db1f5/Python%20Den%20page%20with%20buttons%20open%20-%20teacher%20view.png" alt="Python Den page with buttons open - teacher view.png" />

**Comment by lauracumming** [comment]
[Uploading... Screenshot 2024-07-24 at 17.54.45.png]

**Comment by lauracumming** [comment]
[Levels page - student](https://www.figma.com/design/9pMg7hFzK5YkjcnmwZsFl1/Portal-UI?node-id=275-18126&t=su6ToBpWs0pE39mn-1)

**Comment by lauracumming** [comment]
[Uploading... Python Den page with buttons open - student view.png]

**Comment by evemartin** [comment]
@lauracumming String Manipulation doesn't have any traditional numbered levels in it but the Indeterminate Loops episode right before it does - when the user finishes the last level in the Indeterminate Loops episode, should they be able to go straight to the next level, skipping the String Manipulation episode entirely, or should they get some kind of other prompt to go back to the main levels page instead?

**Comment by lauracumming** [comment]
Good question. It's tricky without the embedded text editor. Maybe go back to levels page and it opens the relevant section? Does that make sense?

**Comment by lauracumming** [comment]
Then they have the option to either open the worksheet or skip?

**Comment by evemartin** [comment]
Handover notes: there are just a few things left to do for this task!

- [ ] there are still some resource links missing - right now these are marked with "TODO"
- [ ] some parts of the PR can be optimised - some repeated bits of code in `python_den_level_selection.html` could be extracted into a custom HTML element, and there's one hardcoded worksheet/IDE level (at the end of the "Counted Loops Using While" episode that might be better if not hardcoded
- [ ] we still need to add the functionality Laura mentioned above: when the user gets to the end of an episode that's followed by an episode with no levels, they should get directed back to the main level selection page instead of the next level (since that would skip over the next episode with no levels)

**Comment by lauracumming** [comment]
Couldn't see these when I clicked to continue. I wasn't logged in - is this an edge case that we need different messaging for?

**Comment by lauracumming** [comment]
LGTM (apart from 'next level')

**Comment by lauracumming** [comment]
Broken link in Procedures episode

![Image](https://github.com/user-attachments/assets/7ff2e1bd-3df2-4503-adaf-315c936710ae)

**Comment by faucomte97** [comment]
But actually since it's not fully deployed yet we should fix it in the initial migration

**Comment by faucomte97** [comment]
@lauracumming @evemartin correct me if I'm wrong but it doesn't look like we have a worksheet for that?

**Comment by lauracumming** [comment]
Ah let me take a look. It may have not saved

**Comment by lauracumming** [comment]
![Screenshot 2024-08-29 at 12 48 02](https://github.com/user-attachments/assets/31cee8fe-1f80-45ba-bc6b-d369b47bcf44)
This is the list for the episodes

**Comment by lauracumming** [comment]
LGTM

**Comment by faucomte97** [comment]
Depth? You mean height? @evemartin

**Comment by lauracumming** [comment]
LGTM, apart from I just noticed the styling for the _inactive_ button isn't consistent with the newsletter button.

![Image](https://github.com/user-attachments/assets/f5e9515d-ffea-4e06-9910-2e54172611f6)
![Image](https://github.com/user-attachments/assets/271475a0-d0fc-4826-b0d0-0dd6a0e2be26)
