### ISSUE TITLE
Replace cows with pigeon in City theme

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/rapid-router#1674]
## Task Description
[Task 443](https://github.com/ocadotechnology/codeforlife-design/issues/443) needs to be completed before this task can be started.

The level editor has cows that you can place on the road (and eventually, just around on the map).
The cows make sense in the Grass, Farm and Snow themes but not so much in the City theme - so we need to replace the cows with the pigeon.

## Acceptance Criteria
- [ ] When selecting the City theme, the cow should be replaced with the pigeon.
- [ ] For the pigeons, play the sound file chosen for the pigeon when the van sounds the horn instead of the cow sound.
- [ ] Rename the label from "Cows:" to "Pigeons:" when the City theme is selected.
- [ ] The "cows" block needs to be updated, if possible, so that if the City theme is selected it reads "pigeons" and has the image of the pigeon instead. If not feasible, replace the block to say "animals" instead.

![image](https://github.com/ocadotechnology/rapid-router/assets/33633200/c8264da2-a0cb-4577-bc8d-345ca58def5b)

**Comment by lauracumming** [comment]
@evemartin could you attach the cow svg or eps here please? I can't locate it on our server.

**Comment by lauracumming** [comment]
Some inspiration:<img width="401" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzRnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de63aeedd320a5f96bf38c74f4a8f499839bad0f/Screenshot%202024-07-31%20at%2009.44.41.png" alt="Screenshot 2024-07-31 at 09.44.41.png" />

<img width="508" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzhnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdc630687e4b279b4814281a4452c46177bc7603/Screenshot%202024-07-31%20at%2009.44.24.png" alt="Screenshot 2024-07-31 at 09.44.24.png" />

<img width="624" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEFnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--adc1bc9574468dcef586431e3f925264cfa9d5df/Screenshot%202024-07-31%20at%2009.44.16.png" alt="Screenshot 2024-07-31 at 09.44.16.png" />

**Comment by evemartin** [comment]
Here is the cow svg! It is called Clarice.svg in the repo, maybe that's the name of the cow 
![Clarice](https://github.com/user-attachments/assets/e3ca2776-8d21-4f0b-80b1-86fcb85985bb)

**Comment by evemartin** [comment]
This task is ready for review!

**Comment by lauracumming** [comment]
LGTM

**Comment by lauracumming** [comment]
LGTM
