### ISSUE TITLE
Build levels for Python Den

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1685]
## Task Description
We would like to create some new levels for the Python Den for the section: Selection in a while loop (14-25)
There is also a set of levels that are copies or additions (26-40)

## Acceptance Criteria
- [ ] Build new levels using examples from Dev account
- [ ] Remap existing levels and remove from Rapid Router where applicable
- [ ] Apply new colour scheme to side bar

### Analytics Requirements
- [ ] Level attempts 

### Copywrite Requirements
- [ ] Level title, level instruction and level hint

Link to docs:https://docs.google.com/document/d/14qjWrbvUX6qONgiYYBsW5KpjpfQR9liYudIuInmFZMU/edit?usp=sharing
https://docs.google.com/document/d/1y_HvqeOQ9gY4IABN47XEYjNSDwNqWVlZm02psUtibMA/edit?usp=sharing

**Comment by lauracumming** [comment]
This didn't load for me

**Comment by lauracumming** [comment]
LGTM (apart from 'next level')

**Comment by lauracumming** [comment]
LGTM

**Comment by lauracumming** [comment]
LGTM
