### ISSUE TITLE
Fix generated Python syntax

### ISSUE THREAD

**Issue by evemartin** [ocadotechnology/rapid-router#1707]
## Task Description and Acceptance Criteria

Some of the generated Python commands in the Python Den's Blockly with Python levels need to be changed to be more consistent. This task is to make the following changes:

- [ ] instead of `.is_road("FORWARD")`, the generated Python should be `.is_road_forward()` - similarly for the other directions
- [ ] instead of `.is_traffic_light("RED")`, the generated Python should be `.is_red_traffic_light()` - similarly for green
- [ ] generated `while` loops should not put the condition in parentheses

Further details:

- Go to [Python Den level 15](https://www.codeforlife.education/pythonden/15/).
- Build this program:

![image](https://github.com/user-attachments/assets/a9eda039-96a8-4f40-a79b-7393d93dadcc)

- The Python output should be the following:

![image](https://github.com/user-attachments/assets/f7c23fbc-f8c6-4a46-b329-a6ea49a6aa15)

- You can see the `while` loop's condition is enclosed in parentheses - no need for this. It should just say `while count < 4:`.
- You can the if condition reads `my_van.is_road('FORWARD')` (same for the other conditions if you change the block). Instead it should be `my_van.is_road_forward()` to stay consistent with what the teaching materials and the commands popup use.

There are no Python Den levels that contain traffic lights but you could see the generated Python for the traffic lights block locally if you create a custom Blocky with Python level which has the traffic light condition block enabled. You can do this in [the Level Editor](https://www.codeforlife.education/rapidrouter/level_editor/) - It is for Rapid Router but you can still create Python levels there - bear in mind the level will appear in the Rapid Router page.

## Good places to start

Python generation code for Blockly with Python levels: https://github.com/ocadotechnology/rapid-router/blob/8b28179b9cfecd2db8d51ac4b2671a78130a24d5/game/static/game/js/blocklyCustomBlocks.js

**Comment by bella054** [comment]
I'd like to be assigned to this one please!

**Comment by SKairinos** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#selected

**Comment by lauracumming** [comment]
LGTM

**Comment by faucomte97** [comment]
LGTM
