### ISSUE TITLE
Python den tidy

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1730]
## Task Description
We have a couple of things that we need to tidy up with regards to the Python Den.

## Acceptance Criteria
- [x] Resize top banner to be same as Rapid Router
- [x] Optimise for search engines
- [x] Add tags - did we do this already?

### Analytics Requirements
- [x] track button clicks to Python Den resources (nav bar)
- [x]  track button clicks to Rapid Router resources (nav bar)

### Copywrite Requirements
- [ ] None
