### ISSUE TITLE
Update Rapid Router Student dashboard

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/rapid-router#967]
## Description

**The current RR student dashboard is still in the old portal design.
This includes: The dashboard and the password reset**

### User story:
_**As a** student... **I want** an easy to use game dashboard... **so that** I can easily select my games, view scoreboards and change my password._

## Acceptance criteria
- [x] New wireframes will need to be created in the new style
- [x] Prototypes should be created and tested with users
- [x] Front-end development will be needed to implement the updates

Current design is shown for context:

![Screen Shot 2018-08-13 at 11.01.42.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/eba102d2-07da-4f3b-82ef-dea5da8a59be)

The updated teacher Rapid Router portal design is shown below:

![Screen Shot 2018-08-13 at 13.04.06.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/254f9f93-70b5-4ad4-a42d-d016c55f8a66)

New Wireframe:
![Student Dash Landing L Desktops James.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/ac0e832c-1450-4cae-933e-cc54369ca606)
